### ISSUE TITLE
Create or point to "introduction to Jupyter" materials for educators

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot#37]
## Background

Many people may wish to provide introductory material to the Jupyter ecosystem, both for instructors or for students. We should curate some useful information for this group to help them get started.

## ToDo

- [ ] Determine what kinds of information new instructors would want to know (or would want to share with their students)
- [ ] Prepare a list of links etc that would be useful
- [ ] Incorporate into the pilot hubs documentation (potentially via a standalone set of docs)
