### ISSUE TITLE
Brainstorm an end-of-use questionnaire for instructors

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot#39]
## Background

For instructors that have finished a cycle of use (e.g. after a semester or course ends), we should determine some things that we want to learn from them.

## ToDo

- [ ] Make a draft of questions to ask instructors ([see this draft](https://docs.google.com/document/d/1cvGBUqkg5FJNWPWOQBOocNn8T0_uKcJ2GQxCm3AyHlM/edit))
- [ ] Turn these into a Google Survey
- [ ] Send to first few people finishing their deployment
