### ISSUE TITLE
Create an onboarding survey for new instructors

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot#40]
## Background

As new instructors are onboarded to the hub infrastructure, we should try to learn a few things from them to understand how we can best-serve them.

## ToDo

- [ ] Agree on a set of questions to ask ([see this draft](https://docs.google.com/document/d/1UPYjJZPfXlq3x0sYGWWC1b84HY0bbtTo6PXvoYbi6Aw/edit))
- [ ] Turn into a Google form
- [ ] Test with a few new instructors
- [ ] Iterate over time to improve the questions

**Comment by sandeepsainath** [comment]
Requested edit access to the set of questions doc!

**Comment by choldgraf** [comment]
Your Gmail should.be added now. (Note that the doc is almost empty, so you're not missing much haha)

**Comment by sandeepsainath** [comment]
No problem! Was just about to add stuff:)

**Comment by sandeepsainath** [comment]
Here is the current draft of the Google form for the onboarding survey: https://docs.google.com/forms/d/1p1kAV6pvtRDV6T76HDlAUkfotBGSWJHX8irM_5Q4ZNo/edit?usp=sharing
