### ISSUE TITLE
Automate check for broken links in documentation and fix those currently broken

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/pilot#76]
### Description

I've spotted some broken links. A sensible approach to mitigate this is to automate link checking that preferably run both on changes and as a cronjob as links can break by external changes as well.

### Implementation

Here is a PR that implements this for one of our repositories: https://github.com/2i2c-org/pilot-hubs/pull/649

It is based on the two code samples below

- [GitHub workflow running a linkcheck command in a Makefile](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/b82dc2df43f700bb0e791a5b41eabc8339ba7ac3/.github/workflows/test-docs.yaml#L23-L43)
- [Makefile entry about linkcheck](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/b82dc2df43f700bb0e791a5b41eabc8339ba7ac3/doc/Makefile#L32-L38)

### Tasks to complete

- [x] Add a linkcheck command to our Makefile
- [x] Add a job within an existing GitHub workflow, or add a dedicated GitHub workflow to run linkcheck on changes to docs
- [x] Fix currently broken links
- [x] Do the above for
  - [x] pilot-hubs
  - [x] pilot
  - [x] team-compass

**Comment by damianavila** [comment]
This would be really nice thing to have in place!

**Comment by choldgraf** [comment]
this is now done for our major documentation repositories!
